#include<iostream.h>
#include<conio.h>
void main()
{
clrscr();
char ch;
cout<<"Enter a character"<<endl;
cin>>ch;
switch(ch)
{
case 'a':
cout<<"It is a vowel"<<endl;
break;
case 'e':
cout<<"It is a vowel"<<endl;
case 'i':
cout<<"It is a vowel"<<endl;
break;
case 'o':
cout<<"It is a vowel"<<endl;
break;
case 'u':
cout<<"It is a vowel"<<endl;
break;
default:
cout<<"Not a vowel"<<endl;
}
getch();
}